### ISSUE TITLE
68.1.1 on Linux breaks 5.0.0-beta1

### ISSUE THREAD

**Issue by rkoktan** [ExchangeCalendar/exchangecalendar#305] opened 2019-10-07 18:26 UTC
I just had TB 68.1.1 pushed to me and it breaks 5.0.0-beta1... "Exchange Calendar is incompatible with Thunderbird 68.1.1"... any chance there is a quick fix?

Thanks,
Rob

**Comment by Oskar1983** [comment] 2019-10-08 09:27
Duplicate of #277

**Comment by gdraheim** [comment] 2019-10-08 14:33
It's Opensuse 15.1 in my case.

**Closed** 2019-10-08 17:12 UTC
