### ISSUE TITLE
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized URL:https://outlook.office365.com/EWS/Exchange.asmx

### ISSUE THREAD

**Issue by chorus12** [ExchangeCalendar/exchangecalendar#55] opened 2017-07-13 09:56 UTC
Hello, I am using office365 for business and wanted to configure GAL to be in sync with TB. 
When configuring the account get the following error:
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://outlook.office365.com/EWS/Exchange.asmx

**Comment by rucoder** [comment] 2017-07-13 17:18
I have the same issue. Either add-on cannot fetch password from outlook account settings or... btw, Why don't just let user enter password?

**Comment by advancingu** [comment] 2017-07-13 18:59
Hi, this appears to be a duplicate of #49.

**Closed by advancingu** 2017-07-13 18:59 UTC
