### ISSUE TITLE
Can't add outlook.com calendar

### ISSUE THREAD

**Issue by ziyuefl** [ExchangeCalendar/exchangecalendar#102] opened 2017-10-08 15:03 UTC
On the add new calendar window, although not being asked for the password, after clicking on Check Server and Mailbox, the following error prompts:

HTTP Server error 503: Service unavailable
URL:https://outlook.office365.com/EWS/Exchange.asmx  (Code -19)

HTTP Server error 503: Service unavailable
URL:https://outlook.com/EWS/Exchange.asmx (Code -19)

**Comment by advancingu** [comment] 2017-10-10 20:56
Thanks for reporting this issue. It sounds like a duplicate of #83 so I'm closing this one here until we have sufficient information that this is a separate issue.
It would be helpful if you can provide debug log content of the time when a connection attempt was made (logging can be turned on in preferences).

**Closed by advancingu** 2017-10-10 20:56 UTC

**Comment by Trim** [comment] 2017-10-11 18:16
IIRC, `outlook.com` replaces the old `hotmail.com` free webmail service.

As `outlook.com` is free too, I suppose Microsoft doesn't expose the Exchange Web Services outside their server.
