### ISSUE TITLE
Not compatible  with TB 60

### ISSUE THREAD

**Issue by EricV** [ExchangeCalendar/exchangecalendar#178] opened 2018-04-24 08:58 UTC
I know it is not out yet but it will be the next ESR version so it is worth testing especially with lightning redesign to cope with UI chnages.

**Comment by EricV2** [comment] 2018-04-25 06:29
Well, I was suspecting that because I know it is a major overhaul with most all plugin code left behind. Thanks for your effort anyway as I depend on it to cope with most company using exchange and outlook. 

Maybe it is time to switch to kmail if the akonadi exchange support matures enough in the mean time.

**Comment by Castiontone** [comment] 2018-04-25 06:46
Hey Trim, 

Thank you for you work. I only recently learned of your fork of the Ericsson version and the 4.0.0 beta5 versions work quite well. Sorry to hear (but fully understandable) the project ends. 

Thanks!

**Comment by ydelau** [comment] 2018-04-25 07:05
Hi Trim,

Thanks for your investment in the project. I will try to see if DAVmail solution can be useful in my case. 

Anyway, as I use Thunderbird on Ubuntu LTS releases, it’s still expected to be TB 52 for a few months at least. 

Is it planned to release a « final » 4.0.0 version of the extension based upon the last beta? 

Thanks again for your work and your attempt to move forward toward TB60 codebase. 

On my (very little) spare time, I’ll see if I can have a look to the source code and if I can do something to help. 

Best regards

**Comment by advancingu** [comment] 2018-04-25 20:59
@Trim Without you this project would have been dead, so thanks a lot for all your work since I forked (from the previous fork)! Personally, I am a bit puzzled that there appears to be zero support from Mozilla, even though Exchange support is an absolute must have feature for email applications in many corporate settings. But I guess that's how they have decided to spend their resources.

I was also thinking about a license based model for this project to be able to fund development, however there is also [this](https://github.com/rkent/exquilla/wiki/Free) by @rkent which sounds quite negative.

I'll try out the alternatives as well.

And for the record, this is what is needed for Thunderbird 60 compatibility: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

**Comment by oaxjogi** [comment] 2018-04-26 06:01
Thx to all contributors that I do not need to work with Outlook :-) If we need money to support the gang whats about using patreon? E.g. Patrick Wardle and his OS X security tools are still free but you can support his work by spending money on a monthly basis and get some more (e.g. betas, ...). I would support this project.

**Comment by enozkan** [comment] 2018-04-27 23:17
@Trim , @advancingu , the Ericcson folk and the original author (@1stsetup): Thanks for all the work! It is a pity the project can't go further.

**Comment by enzolis** [comment] 2018-04-28 12:25
Hi Trim,


thanks for the good work and keeping this plugin alive.

I am a changer from Davmail to exchangecalendar (maybe 3 years ago?). 
The major advantage for me was that EC-plugin is able to use Kerberos 
authentication.

IIRC Davmail was also able to use a Kerberos ticket, but that does not 
help in server mode (everybody uses the same credentials).


Anyway, thanks for the effort and best regards,

  Thimo


Am 25.04.2018 um 08:20 schrieb Adrien Dorsaz:

**Comment by Mechtilde** [comment] 2018-04-29 05:51
Hello to all developers of this package,

I'm unhappy to read that this project will stop. Thanks for your great work.

The consequence is I will also have to stop packaging to for Debian as calendar-exchange-provider.

Best regards

Mechtilde

**Comment by BenjamenMeyer** [comment] 2018-04-30 20:09
Davmail won't work in my situation either. I've used it in the past and when it works, it works; but it breaks often. ExchangeCalendar has been awesome - I wish I could do more JS code to help it out. Hope the community at large can help out.

**Comment by RobertZenz** [comment] 2018-04-30 21:03
@Trim Do you know what changes are required or can you upload your modified code so far?

**Comment by BenjamenMeyer** [comment] 2018-04-30 21:07
@advancingu it's not a surprise Mozilla isn't doing anything. IIRC Thunderbird is now entirely a community effort as Mozilla has tried to divest itself of TB. I think that process might have stalled with Mozilla continuing to provide some resources (build servers, etc) and the community running everything else...I don't fully recall though.

**Comment by Trim** [comment] 2018-05-01 05:04
@RobertZenz you'll find on issue #136 the links to Thunderbird guides about migration to post 57.

On my [fork](https://github.com/Trim/exchangecalendar) you'll find some attempts to automatically update code with bas scripts. See branches thunderbird-60 , replace-for-each-var and ec-4.1-replace-for-each-loop (iirc, none is working).

Ah and don't forget branch current-lightning-beta which has some required changes for Thunderbird betas up to version 56.

**Comment by gitman0** [comment] 2018-05-15 21:10
i would gladly donate to keep this project going. not looking forward to switching to gnome evolution.

**Comment by mattiaverga** [comment] 2018-05-21 17:09
I'd suggest you to have a look at https://github.com/jobisoft/TbSync
I've just tried it and it seems to work quite good. Maybe it would be better to help that new project (which declares itself to be already compatible with TB 60+) rather than trying to rewrite exchangecalendar.

**Comment by oaxjogi** [comment] 2018-05-22 06:26
TbSync did not work for me - it was successfully connected but saw nothing :-(

**Comment by monperrus** [comment] 2018-05-23 18:47
If you're on Linux, you may also consider using the evolution mail/calendar client together with the evolution-ews connector, it works well.

**Comment by Thomas-1985** [comment] 2018-05-23 18:50
Yeah unfortunately allmost all clients in the company i work for are on Windows 10/Thunderbird

**Comment by Trim** [comment] 2018-05-24 19:17
For changes on Thunderbird 61+, I was referring to [this discussion](https://groups.google.com/forum/#!topic/tb-planning/mDj7fFKKPOk).

As Exquilla say it will be available for Thunderbird 60, I wanted to know how many cost a License to use for my personal use. On their [shop](http://mesquilla.net/buylicense.html), they share too some doubts about the future (emphasis from me):

> Beginning in March 2018, ExQuilla is no longer selling licenses, but instead is giving out licenses without charge. The are multiple reasons for this, but the main reason is that purchased licenses are valid for one year, but looking at the ongoing changes in Thunderbird, **we are not confident that we can support ExQuilla in versions of Thunderbird that will be current after March 2019.**

**Comment by oaxjogi** [comment] 2018-05-24 19:55
ExQuilla is only for Mail and Addressbook not for Calendars :-(

**Comment by llange** [comment] 2018-08-15 16:02
Hi, I added some patches to @Trim patches (cf https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-385600206 ) and I managed to have a working calendar on thunderbird 60.
More tests are needed, so if people want to have a look at it please check this pull request: #188

**Comment by gitman0** [comment] 2018-08-15 16:07
very exciting...

**Comment by llange** [comment] 2018-08-18 01:03
Hi, I reworked my patch and I managed to have a working calendar on thunderbird 60.

More tests are needed, so if people want to have a look at it please check this pull request: #189 and the corresponding branch.

**Comment by BenjamenMeyer** [comment] 2018-08-18 04:55
@llange cool - not as bad as I thought it would be based on what others were saying. Seems to be primarily related to updates to JS - for the better IMHO as it makes it more readable. I'm not a TB dev or TB Extension dev. Left one comment regarding something I saw - just curious about the change.

Any how, my $0.02

**Comment by gtatgh** [comment] 2018-08-20 11:41
@llange I have tried your branch and have an issue. My calender seems to work, but shared calenders doesn't.

**Comment by llange** [comment] 2018-08-23 10:36
Hi @gtatgh , could you please have a look at the latest changes in this branch and see if they improve your experience ?
And if possible - could you please follow up the discussion directly in #189 so that everybody can discuss there and help making this patch working ? Thanks

**Comment by moritz-ghc** [comment] 2018-09-01 13:34
Hi Trim,

Many thanks for all your good work on this plugin and keeping it alive! I'm sorry that this project ends, but can fully understand that things can change over time. I'll have a closer look at @llange's development and hope that we can keep a solid MS Exchange Support going. I fear that TB without Exchange support won't have much of a future...

Many thanks again!

Moritz

**Comment by Trapulo** [comment] 2018-09-05 09:35
I'd like to support developers with tests, but I cannot compile sources. Is there any way to have a build of the current dev version?
thanks

**Comment by Mechtilde** [comment] 2018-09-15 05:01
You can also test TbSync which works in some configurations very well with TB 60
https://github.com/jobisoft/TbSync

**Comment by advancingu** [comment] 2018-09-30 10:27
Fyi, I just set up a new branch `v5.0.0-alpha1` to track development of a version with Thunderbird 60 compatibility.

**Comment by zioalex** [comment] 2018-10-08 12:47
@advancingu  just cloned the repo but the compatibility in the branch v5.0.0-alpha1 is still set < v59 therefore I could not install it in TB60. I just updated the install.rdf.template to allow the installation and rebuilt.

After it I tried to configure it setting up the Calandar type to "Microsoft Exchange..." and the location to  https://outlook.office365.com/EWS/Exchange.asmx

But I get the follow error:
![image](https://user-images.githubusercontent.com/3593840/46609600-c3cd7900-cb08-11e8-8bd7-be94fdfa890d.png)

**Comment by sleeksorrow** [comment] 2018-10-10 12:37
@zioalex you should try again. Most of the work on TB60 compatibility by @llange has been merged just some hours ago. I just tried right now and it worked flawlessly for me.

**Comment by zioalex** [comment] 2018-10-10 14:55
Cool! Yes I tried and now it works smoothly.
I just tried to create an event and invited a guy but I cannot see his and
my availability.

Alessandro Surace
[image: https://twitter.com/zioale] <https://twitter.com/zioale>

**Comment by benwaugh** [comment] 2018-10-11 08:33
Great. This has fixed the problem I had where Thunderbird crashed if I clicked in the description field of an event. For anyone who (like me) didn't know how to get the .xpi file to install:-
```
git clone -b v5.0.0-alpha1 https://github.com/ExchangeCalendar/exchangecalendar.git
cd exchangecalendar/
make build
```

**Comment by benwaugh** [comment] 2018-10-11 15:48
I spoke too soon! Despite unsubscribing from my work (Office 365) calendar and re-adding it, some events (including everything for tomorrow) are just not showing up. They are present in my Android phone calendar and in OWA.

**Comment by bberndt** [comment] 2018-10-15 17:15
confirm. My events are all messed up, and not seeing everything. :(
Makes one really consider Evolution, but I have some serious problems with that idea too: Can't have POP email, and exchange calendar, at the same time.

**Comment by bberndt** [comment] 2018-10-15 20:00
Looks like all new(er) meetings aren't showing up.  Probably anything new since installing these various builds to get it to work with TB 60.

**Comment by awldickinson** [comment] 2018-10-16 14:11
I deeply want to thank you @Trim - and to everyone else who contributed - for all your work maintaining the ExchangeCalendar plugin for as long as you have.  I've really preferred to use TB over any other client, but with my organization's reliance on Exchange.. this _may_ be the end of my journey.

In case anyone is needing an immediate solution that seems to be working for me, I've been able to move to evolution with the evolution-ews connector, as per @gitman0 above.

**Comment by advancingu** [comment] 2018-10-16 17:08
[Referencing a comment](https://github.com/ExchangeCalendar/exchangecalendar/issues/136#issue-284644741) with information about changes needed for TB60 compatibility.

**Comment by minibiti** [comment] 2018-10-17 09:59
The code from branch v5.0.0-alpha1seems to work for me, against Office365

**Comment by daemonkeeper** [comment] 2018-10-17 13:40
Is there a way to enable event logging or debug output for this plugin? I am able to see all events, but I cannot create new calendar events of any sort, including but not limited to invites, or events created by myself. 

The creation dialogue appears in the latter case, I can save it, but they just don't appear in the calendar. Looking at third party applications or the web interfaces, I do not see the events at all. 

Would provide more input if you tell me how.

**Comment by advancingu** [comment] 2018-10-17 13:43
@daemonkeeper Logging does exist but is quite clunky (you used to be able to turn it on in the calendar configuration window). I actually want to look at it next so that it becomes easier to debug all the issues that now appeared with TB60.

**Comment by cirulls** [comment] 2018-10-17 14:31
I installed manually the .xpi from [v5.0.0-alpha1](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v5.0.0-alpha1) and so far it works fine for me on Hosted Exchange. I'm providing a screenshot of my (obfuscated) settings in case it could be useful to other people. Thanks for releasing v5.0.0-alpha1, very much appreciated!

![image](https://user-images.githubusercontent.com/13256236/47093628-86ac6980-d221-11e8-8247-82c976f0159b.png)

**Comment by benwaugh** [comment] 2018-10-17 15:32
I've installed v5.0.0-alpha1, unsubscribed and re-added my work calendar (Office 365) and I'm still missing some events. The ones that I've noticed are missing are meetings that were created by someone else, which I was invited to. Other events that I have been invited to are showing up, and I don't know what the pattern is. Could be related to when they were added to my calendar, or could be something else.

**Comment by bberndt** [comment] 2018-10-17 22:45
![screenshot from 2018-10-17 16-43-25](https://user-images.githubusercontent.com/12832800/47120421-d859f180-d22b-11e8-9287-fe92a4d87d4d.png)
I see things like this when I try to respond to a meeting request; it never finishes running. 
If i quit, and then reopen Thunderbird most of the time, the meeting request gets added to my Outlook Calendar, and I'll see it.

**Comment by David-S-Morgan** [comment] 2018-10-18 14:16
I've installed v5.0.0-alpha1 as well -- thanks so much for updating it.

I'm having a similar issue as @benwaugh (though I didn't try removing and re-adding my calendar).  We use O365, and for me, glancing at the calendar now and a few weeks ahead, it looks like it consistently isn't showing any of my meetings (whether I created them or was invited to them), but only on **Fridays**.  From a quick check, other days seem fine, though I don't schedule much on my work calendar for Sat/Sun, so I can't verify that those days are fine.

Now if only the plugin could make it so that I don't actually have those Friday meetings, and not just disable showing them, I'd be all set! :-)

**Comment by benwaugh** [comment] 2018-10-18 14:28
Aha! It does look as if my missing meetings are all on Fridays, but not all Friday meetings are missing:
- I can see some all-day events I created earlier on Fridays.
- I can create new meetings on Fridays in Thunderbird, and they show up in OWA and my Android calendar.
- I even just created an event in OWA for a Friday and it did show up in Thunderbird.

**Comment by David-S-Morgan** [comment] 2018-10-18 14:42
@benwaugh - I can confirm exactly what you observe in your bullet points on my own calendar. Your bullet #3 gave me an idea for a temporary workaround (sort of).  If it's an event you created, just update something trivial in the event (e.g. add 1 minute to the end time) and save in OWA.  Sync on Thunderbird and the event should show up.  For events you're invited to but haven't accepted, accept it in OWA and it should then show up in Thunderbird.  Haven't figured out a workaround for already-accepted events, I just create a parallel event for the present.

**Comment by advancingu** [comment] 2018-10-18 14:49
I'm also missing some events in my calendar. Spent a long time yesterday to improve logging so that it will become easier to find root causes for issues like this. Will hopefully be able to push this code later today.

**Comment by nparsons999** [comment] 2018-10-18 16:29
Working well for me on Ubuntu 18.04 office 365 calendar. Both the pre-built and my own build .xpi worked. Two minor problems.
1. When a meeting reminder pops up, I usualy have to dismiss it several times before the pop-up stops reshowing. Sometimes it is never dismissed and I have to exit and restart TB. This was also a problem in 4.0.0 so its not new.
2. A new problem. When a reminder pops up with a link say to a webex/zoom meeting, I can't click on the link and launch the webex meeting. I have to cut/paste the link into firefox URL bar. If I do click on link, I get javascript application error window eg. 'Do not know how to handle this reference:https://tivo.zoom.us/j/1234567890'
Otherwise great work guys!

**Comment by David-S-Morgan** [comment] 2018-10-18 17:00
@advancingu Good luck! I'm happy to help do specific tests if it will help.

**Comment by advancingu** [comment] 2018-10-18 20:20
I'm closing this issue since it contains too many separate issues. Also, I believe with v5.0.0-alpha1 general TB60 compatibility was already completed.

The issue of some calendar entries not showing will be tracked in #203.

Please open a new issue in case none exists yet for other issues.

@David-S-Morgan I pushed PR #202 with logging improvements. Would be great if you can give it a try.

**Closed by advancingu** 2018-10-18 20:20 UTC

**Comment by BenjamenMeyer** [comment] 2018-10-25 19:48
Confirm v5.0.0-alpha1 is TB60 compatible. Now if they'd just properly release the Lightning plugin again via the add-ons functionality.... :crying_cat_face:

**Comment by wagner-certat** [comment] 2018-10-29 12:29
@BenjamenMeyer there are still lots of synchronization bugs

**Comment by daemonkeeper** [comment] 2018-10-29 12:38
Nobody disagreed. I do also still have my issue. However,  it makes sense to track them in separate issues. 

As soon as I would get some useful debug logging, I'd report mine again ;-)

**Comment by wagner-certat** [comment] 2018-10-29 12:52
> As soon as I would get some useful debug logging, I'd report mine again ;-)

#202 does add debug logging but I don't know how to get the logs.

**Comment by likeuwill** [comment] 2018-11-07 08:03
You also need reinstall a Lightning add-on. Remove it from **Tools→ Add-ons**
Install new version from terminal `sudo apt install xul-ext-lightning`

**Comment by pnad** [comment] 2018-11-07 13:07
@nparsons999 I create fix for it https://github.com/ExchangeCalendar/exchangecalendar/pull/214

**Comment by dmadeka** [comment] 2019-01-16 21:37
Is there a plan to get this compatible with TB 60.2.1? The current build from source doesnt seem to work

**Comment by advancingu** [comment] 2019-01-16 21:39
@dmadeka What branch did you build from?

**Comment by dmadeka** [comment] 2019-01-16 21:41
Master

**Comment by advancingu** [comment] 2019-01-16 21:48
That's the wrong branch. Please look at the [release history](https://github.com/ExchangeCalendar/exchangecalendar/releases) and you will find the correct branch.

**Comment by dmadeka** [comment] 2019-01-16 21:57
Thanks!
