### ISSUE TITLE
Events on Monday Mornings Do Not Display in the Calendar View

### ISSUE THREAD

**Issue by jamesquilty** [ExchangeCalendar/exchangecalendar#67] opened 2017-08-07 20:10 UTC
Thunderbird 52.2.1 (Mac OS 64-bit); Exchange EWS Provider 4.0.0beta4

This is a long-standing issue, not a new issue with 4.0.0 beta 4. Events scheduled for Monday mornings do not display in the calendar view, but they *do* appear in the Today Pane. The 10-11 am slot seems to be most problematic while 11 am - 12 pm displays in the calendar view. The timezone, just in case it is relevant, is Pacific/Auckland.

 This is definitely a problem with Exchange EWS Provider, because events created in a local calendar for the 10-11 am time slot display without problem.

 An almost certainly related, and perhaps the same, bug is Exchange events for any morning with an end date prior to 11 am failing to display in the Today Pane.

**Comment by Trim** [comment] 2017-08-08 05:18
Hello,

Well, I've never seen such an issue, but my timezone is Europe/Zurich. I also have never noticed that timezone range begins from UTC-12 to UTC+14, it's quiet big !

I think the issue is on event saving, because the event creation/modification dialog has some code about timezones (it seems you can change the timezone of start/end time of the event [1]).

Can you check in another application like the Outlook Web Access (owa) or another app if events appear correctly in them ? Or could you open the event from the Today Pane and check if times in the event details are correctly displayed ?


[1] : In the event dialog, you can add a button to the tool box in the header to hidde/show timezones aside the start / end time event.

**Comment by Trim** [comment] 2017-08-08 06:50
Well, that's really interesting: event in month summary is displayed on Sunday night (I think that's the UTC time), but in the event dialog it's correctly written as Monday morning:

![Timezone display issue](https://cloud.adorsaz.ch/index.php/s/XPS9NTjPfJ1zqOw/download)

**Comment by Trim** [comment] 2017-08-11 14:50
I've just found that there's an option to set the timezone inside the preferences of Lightning / Thunderbird.

Could you check please the value of the time zone in the Thunderbird Preferences dialog (under the Calendar tab) is correctly setted ?

On my side, it was to Europe/Zurich. When I updated it to Pacific/Auckland and restarted Thunderbird, it correctly appeared in the month summary.

**Comment by jamesquilty** [comment] 2017-08-12 04:20
I can confirm that - apart from the display - the events are as-entered. They display correctly in Outlook Web Access, with the correct day and time.

 There is some oddness around the day-week-multiweek-month display in Thunderbird: the 9-11 am event does not display in day-week-multiweek views but does display on the correct day (Monday) in month view.

 I set the time zone in the Thunderbird Preferences many years ago, and confirmed it is Pacific/Auckland. I then set it to Europe/London, restarted, switched back to Pacific/Auckland and restarted. Unfortunately, the same problem appears after the reset of the time zone.

**Comment by Trim** [comment] 2017-08-14 13:03
> There is some oddness around the day-week-multiweek-month display in Thunderbird: the 9-11 am event does not display in day-week-multiweek views but does display on the correct day (Monday) in month view.

Oh, I didnt check other calendar views:

Now, I've made an event which begins on August 14 at 8 am (yesterday, Monday).
When I display calendar with "multiweek" with August 14 as fist date and September 10 as the last one (Monday is first day of the week on my configuration), I don't see my event.

If I click on the left arrow on the left of "Today" text, the displayed range is from August 7 to September 3. With that range, I see correctly events on August 14 at 8 am.

It seems so that only events who has UTC start time corresponding to the non-UTC range selection are shown. That's quiet strange, now I need to check if it's exchangecalendar which define events to be shown and if I can correct it.

**Comment by jamesquilty** [comment] 2017-08-14 21:29
This is definitely a bug in ExchangeCalendar - local and CalDAV calendars do not exhibit this problem.

Changing the preference Calendar -> Views -> General "Start the week on" from Monday (my standard setting) to Sunday yields in week view: (a) Monday morning events in ExchangeCalendar display correctly and (b) Sunday morning events are not displayed.

So, the bug affects the display of morning events on the first day of the week in week view. I also note that this bug appears to affect _all_ ExchangeCalendar morning events in Day view.

**Comment by advancingu** [comment] 2017-08-26 20:48
Fix was merged into `ec-4.0` branch.

**Closed by advancingu** 2017-08-26 20:48 UTC
