### ISSUE TITLE
Thunderbird 60.0 compatibility

### ISSUE THREAD

**Issue by cesdperez** [ExchangeCalendar/exchangecalendar#190] opened 2018-09-06 13:24 UTC
Thunderbird version: 60.0
OS: Arch Linux

I'm trying to install latest beta using the xpi (exchangecalendar-v4.0.0-beta6.xpi built from the repo) and I get `Exchange Calendar could not be installed because it is not compatible with Thunderbird 60.0)`.

**Comment by joelnb** [comment] 2018-09-06 18:58
Might be worth seeing if the code in PR https://github.com/ExchangeCalendar/exchangecalendar/pull/189 works for you - it's working okay for me on the latest thunderbird on Arch.

**Comment by hefayed01** [comment] 2018-09-07 16:26
Hi,

i have installed the latest build on OSX but i have missing events in the calendar.

Any idea why this happening ?

Regards,
Hesham

**Comment by axi92** [comment] 2018-09-14 11:12
I built the branch 'thunderbird-60-2nd-try' but it is still not compatible with Thunderbird 60.
What did you build?
Ubuntu 18.04

**Comment by sleeksorrow** [comment] 2018-09-14 11:34
I'm using
`git clone -b thunderbird-60-2nd-try https://github.com/llange/exchangecalendar.git; cd exchangecalendar; make build`
Result installs without issues

**Comment by bberndt** [comment] 2018-09-14 15:03
I downloaded the zip file, but otherwise the same.  it results in a .xpi file that I then manually install into Thunderbird, on the add-ons page. (removing the old one first)

**Comment by Mechtilde** [comment] 2018-09-15 04:58
I built thunderbird-60-2nd-try under Debian. It builds. I can Install it without problems into TB 60. But I can't configure the connection to an Exchange server.

**Comment by Toromtomtom** [comment] 2018-09-17 09:46
I used the command as suggested by @sleeksorrow and my calendars are active again. Thanks for the patch!

**Comment by benwaugh** [comment] 2018-09-27 13:02
I've been using the version from thunderbird-60-2nd-try since 21st September, and it's been working OK. However, I just tried to edit the description of an event, and found out that Thunderbird crashes as soon as I click in the description tab. Can anyone else reproduce this?

**Comment by kwadroke** [comment] 2018-09-27 16:59
> I've been using the version from thunderbird-60-2nd-try since 21st September, and it's been working OK. However, I just tried to edit the description of an event, and found out that Thunderbird crashes as soon as I click in the description tab. Can anyone else reproduce this?

Yes, I have the same problem. See https://github.com/ExchangeCalendar/exchangecalendar/pull/189#issuecomment-422815887

**Comment by advancingu** [comment] 2018-09-30 10:29
Closing this as a duplicate of #178. Please continue the discussion over there. Thanks!

**Closed by advancingu** 2018-09-30 10:29 UTC
