### ISSUE TITLE
Not possible to add a new calendar anymore

### ISSUE THREAD

**Issue by zioalex** [ExchangeCalendar/exchangecalendar#213] opened 2018-11-06 13:44 UTC
Hi I just retried to add the Calendar because some events were missed. The I could not do it.
I go the follow error in the console:
```
> 1st-setup: Error: Warning: Error during creation of erPrimarySMTPCheckRequest. Err=TypeError: this.logDebug is not a function
> 
>   mivFunctions.js:515
> XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), logLevel: Getter, timeStamp: Getter, message: Getter, errorMessage: Getter, sourceName: Getter, sourceLine: Getter, lineNumber: Getter, columnNumber: Getter, flags: Getter, 21 more… }  mivFunctions.js:520
> 
> 
> calICalendarACLEntry getOwnerIdentities:null
> console.error: 
>   1st-setup: Error: Warning: Error during creation of erPrimarySMTPCheckRequest. Err=TypeError: this.logDebug is not a function
> 
> 
> console.error: 
> Object
>     - QueryInterface = function QueryInterface() { [native code] }
>     - logLevel = 3
>     - timeStamp = 1541510254075
>     - message = [JavaScript Error: "1st-setup: Warning: Error during creation of erPrimarySMTPCheckRequest. Err=TypeError: this.logDebug is not a function|"]
>     - toString = function toString() { [native code] }
>     - errorMessage = 1st-setup: Warning: Error during creation of erPrimarySMTPCheckRequest. Err=TypeError: this.logDebug is not a function|
>     - sourceName = 
>     - sourceLine = null
>     - lineNumber = 0
>     - columnNumber = 0
>     - flags = 0
>     - category = component javascript
>     - outerWindowID = 0
>     - innerWindowID = 0
>     - isFromPrivateWindow = false
>     - stack = undefined
>     - errorMessageName = 
>     - notes = {"length":0}
>     - init = function init() { [native code] }
>     - initWithWindowID = function initWithWindowID() { [native code] }
>     - initWithSanitizedSource = function initWithSanitizedSource() { [native code] }
>     - initWithSourceURI = function initWithSourceURI() { [native code] }
>     - debug = 0
>     - info = 1
>     - warn = 2
>     - error = 3
>     - errorFlag = 0
>     - warningFlag = 1
>     - exceptionFlag = 2
>     - strictFlag = 4
>     - infoFlag = 8
```

I am using Thunderbird 60.2.1 and Lighting 6.2.2.1 coming out of the box with Thunderbird. 
I tried with both v5.0.0-alpha1 and alpha2 the problem is the same.
So at the moment I am out of the order with TB!

**Comment by zioalex** [comment] 2018-11-06 13:46
I looked in the code but I cannot  find out where this error come from. 
common/interface/global/mivFunctions.js
In that lines I have:
```
514     ERROR: function _ERROR(aMessage) {
515         console.error("1st-setup: Error: " + aMessage + '\n');
516         var scriptError = Cc["@mozilla.org/scripterror;1"].createInstance(Ci.nsIScriptError);
517         scriptError.init("1st-setup: " + aMessage, null, null, 0, 0,
518             Ci.nsIScriptError.errorFlag,
519             "component javascript");
520         console.error(scriptError);
521     },
```

**Comment by ruohomaa-ericsson** [comment] 2018-11-07 11:41
Could not reproduce this on my setup and a particular networked calendar, software versions match. I have also cloned and then edited-clone of an existing calendar to add a new calendar (with alpha1) and the new calendar is working.

**Comment by zioalex** [comment] 2018-11-07 12:16
Hi retried with a new profile and I have the same behavior.

**Comment by wrouesnel** [comment] 2018-11-08 01:32
I'm having a similar problem. Somewhere in the javascript that logDebug function is being blanked out (or called in the wrong order).

**Comment by isorochan** [comment] 2018-11-08 16:35
I'm observing same issue

**Comment by zioalex** [comment] 2018-11-11 18:17
Tested pulling the latest version. Same result.

**Comment by advancingu** [comment] 2018-11-11 22:12
@zioalex Did you build from branch `213-logging-fix`? This PR is not yet in a release.

**Comment by wrouesnel** [comment] 2018-11-11 22:30
@advancingu pulled and tested the PR and it fixes calendars for me perfectly thanks!

**Comment by advancingu** [comment] 2018-11-11 23:08
Fixed in #216.

**Closed by advancingu** 2018-11-11 23:08 UTC

**Comment by zioalex** [comment] 2018-11-12 09:32
Nope I didn't try from that branch. Yep now it works also for me. Many thanks.
Thanks @wrouesnel  for the advise.

**Comment by Mechtilde** [comment] 2019-01-07 18:04
I want to open this issue. It doesn't work in version 5.0.0-alpha 2.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918591
