### ISSUE TITLE
5.0.0 beta2 not compatible with Thunderbird 68.4.1

### ISSUE THREAD

**Issue by gambr** [ExchangeCalendar/exchangecalendar#312] opened 2020-01-20 16:56 UTC
I had a 5.0.0 alpha version installed and after Thunderbird update to 68.4.1 it didn't work. I tried to install the beta2 version but I get the same "incompatible" error.

**Comment by jangrewe** [comment] 2020-01-21 14:32
https://github.com/ExchangeCalendar/exchangecalendar/issues/311
https://github.com/ExchangeCalendar/exchangecalendar/issues/308
https://github.com/ExchangeCalendar/exchangecalendar/issues/297
https://github.com/ExchangeCalendar/exchangecalendar/issues/298
https://github.com/ExchangeCalendar/exchangecalendar/issues/300
https://github.com/ExchangeCalendar/exchangecalendar/issues/301
https://github.com/ExchangeCalendar/exchangecalendar/issues/302
https://github.com/ExchangeCalendar/exchangecalendar/issues/305
https://github.com/ExchangeCalendar/exchangecalendar/issues/306
https://github.com/ExchangeCalendar/exchangecalendar/issues/307

i hope you get the point.

**Comment by sleeksorrow** [comment] 2020-01-21 14:45
You missed the most important point to get: #277

This is the one to subscribe whilst all others are just duplicates.

**Comment by jangrewe** [comment] 2020-01-21 14:50
No, you misunderstood the point i was trying to make: this is just another duplicate of all the other duplicates. Getting to #277 was left out as a lesson.

**Comment by sleeksorrow** [comment] 2020-01-21 15:04
Indeed I misunderstood and now get your goal. But I favor to point to the right direction instead to all others ;)

**Comment by gitman0** [comment] 2020-01-21 15:22
is it not possible to have a note about the compatibility issue on the main page? https://github.com/ExchangeCalendar/exchangecalendar

**Comment by sleeksorrow** [comment] 2020-01-21 18:55
You mean something like:

> This extension requires:
> A recent Thunderbird version up to 59.

**Comment by gitman0** [comment] 2020-01-21 22:32
no, because I think it has proven not effective enough.

**Comment by jangrewe** [comment] 2020-01-21 23:04
It's up to 60 anyways. The ESR release works perfectly fine.

**Comment by TokenRing** [comment] 2020-01-23 20:27
Yes, I'm on 60.9.1 and everything is fine. I've disabled all updates until Exchange can work with Lightning again.

**Comment by Grummfy** [comment] 2020-02-04 13:25
any news?

**Comment by jangrewe** [comment] 2020-02-04 14:28
@Grummfy you'll be the first to know if you keep an eye on this page: https://github.com/ExchangeCalendar/exchangecalendar/commits/master

**Comment by tidux** [comment] 2020-02-04 18:44
> It's up to 60 anyways. The ESR release works perfectly fine.

68 is ESR now.

**Comment by jangrewe** [comment] 2020-02-04 19:59
Is it? I can't find any information regarding a new ESR release. Do you have a source?

Either way, there's always this: https://archive.mozilla.org/pub/thunderbird/releases/

**Comment by tidux** [comment] 2020-02-04 21:58
[Every Thunderbird release is an ESR.](https://www.thunderbird.net/en-US/organizations/)

It also matches the Firefox cadence of every 8th release being an ESR: 52 => 60 => 68.

**Comment by advancingu** [comment] 2020-05-01 14:01
As already pointed out, see #277.

**Closed by advancingu** 2020-05-01 14:01 UTC
